@baseUrl = http://localhost:3000

### @name RecadosControllerReceberRecado
GET  {{baseUrl}}/recados

### @name RecadosControllerReceberRecado
GET  {{baseUrl}}/recados/1


### @name RecadosControllerReceberRecado
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Este é um recado de teste 15",
    "de": "João",
    "para": "Maria"
}


### @name AtualizaRecado
PATCH {{baseUrl}}/recados/6
Content-Type: application/json

{ 
    "de": "Teste do Marco",
    "lido": true
}

### @name DeletarRecado
  DELETE {{baseUrl}}/recados/2


### @name PessoaControllerReceberRecado
GET  {{baseUrl}}/pessoas

### @name PessoaControllerReceberRecado
GET  {{baseUrl}}/pessoas/1


### @name PessoaControllerReceberRecado
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
    "nome": "João",
    "password": "senha123",
    "email": "joao@example.com"
}


### @name AtualizaPessoa
PATCH {{baseUrl}}/pessoas/1
Content-Type: application/json

{ 
    "nome": "João Silva",
    "email": "joao.silva@example.com"
}
}

### @name DeletarPessoa
  DELETE {{baseUrl}}/pessoas/1